/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.AudioChapterTimecodes;
import de.evangeliumstaucher.model.ChapterNext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AudioChapter
 */
public class AudioChapterTest {
    private final AudioChapter model = new AudioChapter();

    /**
     * Model tests for AudioChapter
     */
    @Test
    public void testAudioChapter() {
        // TODO: test AudioChapter
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bibleId'
     */
    @Test
    public void bibleIdTest() {
        // TODO: test bibleId
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'resourceUrl'
     */
    @Test
    public void resourceUrlTest() {
        // TODO: test resourceUrl
    }

    /**
     * Test the property 'timecodes'
     */
    @Test
    public void timecodesTest() {
        // TODO: test timecodes
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

}
