/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.BibleSummaryCountries;
import de.evangeliumstaucher.model.Language;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AudioBible
 */
public class AudioBibleTest {
    private final AudioBible model = new AudioBible();

    /**
     * Model tests for AudioBible
     */
    @Test
    public void testAudioBible() {
        // TODO: test AudioBible
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dblId'
     */
    @Test
    public void dblIdTest() {
        // TODO: test dblId
    }

    /**
     * Test the property 'abbreviation'
     */
    @Test
    public void abbreviationTest() {
        // TODO: test abbreviation
    }

    /**
     * Test the property 'abbreviationLocal'
     */
    @Test
    public void abbreviationLocalTest() {
        // TODO: test abbreviationLocal
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'countries'
     */
    @Test
    public void countriesTest() {
        // TODO: test countries
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameLocal'
     */
    @Test
    public void nameLocalTest() {
        // TODO: test nameLocal
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'descriptionLocal'
     */
    @Test
    public void descriptionLocalTest() {
        // TODO: test descriptionLocal
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'relatedDbl'
     */
    @Test
    public void relatedDblTest() {
        // TODO: test relatedDbl
    }

}
