/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.ChapterSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Book
 */
public class BookTest {
    private final Book model = new Book();

    /**
     * Model tests for Book
     */
    @Test
    public void testBook() {
        // TODO: test Book
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bibleId'
     */
    @Test
    public void bibleIdTest() {
        // TODO: test bibleId
    }

    /**
     * Test the property 'abbreviation'
     */
    @Test
    public void abbreviationTest() {
        // TODO: test abbreviation
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nameLong'
     */
    @Test
    public void nameLongTest() {
        // TODO: test nameLong
    }

    /**
     * Test the property 'chapters'
     */
    @Test
    public void chaptersTest() {
        // TODO: test chapters
    }

}
