/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Meta
 */
public class MetaTest {
    private final Meta model = new Meta();

    /**
     * Model tests for Meta
     */
    @Test
    public void testMeta() {
        // TODO: test Meta
    }

    /**
     * Test the property 'fums'
     */
    @Test
    public void fumsTest() {
        // TODO: test fums
    }

    /**
     * Test the property 'fumsId'
     */
    @Test
    public void fumsIdTest() {
        // TODO: test fumsId
    }

    /**
     * Test the property 'fumsJsInclude'
     */
    @Test
    public void fumsJsIncludeTest() {
        // TODO: test fumsJsInclude
    }

    /**
     * Test the property 'fumsJs'
     */
    @Test
    public void fumsJsTest() {
        // TODO: test fumsJs
    }

    /**
     * Test the property 'fumsNoScript'
     */
    @Test
    public void fumsNoScriptTest() {
        // TODO: test fumsNoScript
    }

}
