/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.Passage;
import de.evangeliumstaucher.model.SearchVerse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchResponse
 */
public class SearchResponseTest {
    private final SearchResponse model = new SearchResponse();

    /**
     * Model tests for SearchResponse
     */
    @Test
    public void testSearchResponse() {
        // TODO: test SearchResponse
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'verseCount'
     */
    @Test
    public void verseCountTest() {
        // TODO: test verseCount
    }

    /**
     * Test the property 'verses'
     */
    @Test
    public void versesTest() {
        // TODO: test verses
    }

    /**
     * Test the property 'passages'
     */
    @Test
    public void passagesTest() {
        // TODO: test passages
    }

}
