/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.SectionNext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Section
 */
public class SectionTest {
    private final Section model = new Section();

    /**
     * Model tests for Section
     */
    @Test
    public void testSection() {
        // TODO: test Section
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bibleId'
     */
    @Test
    public void bibleIdTest() {
        // TODO: test bibleId
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'chapterId'
     */
    @Test
    public void chapterIdTest() {
        // TODO: test chapterId
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'verseCount'
     */
    @Test
    public void verseCountTest() {
        // TODO: test verseCount
    }

    /**
     * Test the property 'firstVerseId'
     */
    @Test
    public void firstVerseIdTest() {
        // TODO: test firstVerseId
    }

    /**
     * Test the property 'lastVerseId'
     */
    @Test
    public void lastVerseIdTest() {
        // TODO: test lastVerseId
    }

    /**
     * Test the property 'firstVerseOrgId'
     */
    @Test
    public void firstVerseOrgIdTest() {
        // TODO: test firstVerseOrgId
    }

    /**
     * Test the property 'lastVerseOrgId'
     */
    @Test
    public void lastVerseOrgIdTest() {
        // TODO: test lastVerseOrgId
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }

}
