/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SectionSummary
 */
public class SectionSummaryTest {
    private final SectionSummary model = new SectionSummary();

    /**
     * Model tests for SectionSummary
     */
    @Test
    public void testSectionSummary() {
        // TODO: test SectionSummary
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bibleId'
     */
    @Test
    public void bibleIdTest() {
        // TODO: test bibleId
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'firstVerseId'
     */
    @Test
    public void firstVerseIdTest() {
        // TODO: test firstVerseId
    }

    /**
     * Test the property 'lastVerseId'
     */
    @Test
    public void lastVerseIdTest() {
        // TODO: test lastVerseId
    }

    /**
     * Test the property 'firstVerseOrgId'
     */
    @Test
    public void firstVerseOrgIdTest() {
        // TODO: test firstVerseOrgId
    }

    /**
     * Test the property 'lastVerseOrgId'
     */
    @Test
    public void lastVerseOrgIdTest() {
        // TODO: test lastVerseOrgId
    }

}
