/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.VerseNext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Verse
 */
public class VerseTest {
    private final Verse model = new Verse();

    /**
     * Model tests for Verse
     */
    @Test
    public void testVerse() {
        // TODO: test Verse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'orgId'
     */
    @Test
    public void orgIdTest() {
        // TODO: test orgId
    }

    /**
     * Test the property 'bibleId'
     */
    @Test
    public void bibleIdTest() {
        // TODO: test bibleId
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'chapterId'
     */
    @Test
    public void chapterIdTest() {
        // TODO: test chapterId
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'verseCount'
     */
    @Test
    public void verseCountTest() {
        // TODO: test verseCount
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }

}
