myHostname: https://reinaldus.fritz.box:8443
server:
    port: 8443
    ssl:
        enabled: true
        key-store: ./gd.p12
        key-store-password: changeit
        keyAlias: gd
        keyStoreType: PKCS12
spring:
    jpa:
        hibernate:
            ddl-auto: update
logging:
    level:
        de.evangeliumstaucher: trace
        web: info