cache: true
myHostname: https://evangeliumstaucher.nobler.tech
logging:
    level:
        de:
            evangeliumstaucher: WARN
        org:
            crosswire: off
            springframework:
                security: WARN
            thymeleaf: ERROR
        root: warn
        web: WARN
security:
    require-ssl: true
server:
    port: 443
    ssl:
        key-store: /home/ubuntu/myp12file.p12
        keyAlias: your_alias_name
        keyStoreType: PKCS12
        key-store-password: 'your_pass'
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 2048
spring:
    profiles:
        default: default,db,creds,prodDB,accounts,logging
