cache: true
hostname: http://evangeliumstaucher.nobler.tech
logging:
    level:
        de:
            evangeliumstaucher: DEBUG
        org:
            crosswire: off
            springframework:
                security: INFO
            thymeleaf: ERROR
        root: INFO
        web: INFO
security:
    require-ssl: true
server:
    port: 443
    ssl:
        key-store: /etc/letsencrypt/live/evangeliumstaucher.nobler.tech/myp12file.p12
        keyAlias: your_alias_name
        keyStoreType: PKCS12
    tomcat.max-threads: 4

spring:
    profiles:
        default: default,db,creds,accounts,logging
