myHostname: https://reinaldus.fritz.box:8443
server:
  port: 8443
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    de.evangeliumstaucher: debug
    web: info
  file:
    name: .logs/app.log

spring.ssl.bundle.jks:
  server:
    reload-on-update: true
    key.alias: gd
    keystore:
      location: gd.p12
      type: PKCS12
      password: changeit
