spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
