myHostname: https://reinaldus.fritz.box:8443
server:
    port: 8443
spring:
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
logging:
    level:
        de.evangeliumstaucher: debug
        web: info