cache: true
myHostname: https://evangeliumstaucher.nobler.tech
logging:
  level:
    de:
      evangeliumstaucher: WARN
    org:
      crosswire: off
      springframework:
        security: WARN
      thymeleaf: ERROR
    root: warn
    web: WARN

spring.ssl.bundle.jks:
  server:
    reload-on-update: true
    key.alias: gd
    keystore:
      location: gd.p12
      type: PKCS12
      password: changeit
server:
    port: 443
    ssl:
        key-store: /home/ubuntu/myp12file.p12
        #key-store: gd.p12
        keyAlias: your_alias_name
        keyStoreType: PKCS12
        key-store-password: 'your_pass'
        #key-store-password: 'changeit'
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 2048
spring:
  profiles:
    default: default,db,creds,prod,accounts,logging
