/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher;

import de.evangeliumstaucher.invoker.ApiException;
import de.evangeliumstaucher.model.InlineResponse200;
import de.evangeliumstaucher.model.InlineResponse2001;
import de.evangeliumstaucher.model.InlineResponse20012;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BiblesApi
 */
@Ignore
public class BiblesApiTest {

    private final BiblesApi api = new BiblesApi();

    
    /**
     * 
     *
     * Gets a single audio &#x60;Bible&#x60; for a given &#x60;audioBibleId&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAudioBibleTest() throws ApiException {
        String audioBibleId = null;
                InlineResponse20012 response = api.getAudioBible(audioBibleId);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets an array of audio &#x60;Bible&#x60; objects authorized for current API Key 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAudioBiblesTest() throws ApiException {
        String language = null;
        String abbreviation = null;
        String name = null;
        String ids = null;
        String bibleId = null;
        Boolean includeFullDetails = null;
                InlineResponse200 response = api.getAudioBibles(language, abbreviation, name, ids, bibleId, includeFullDetails);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a single &#x60;Bible&#x60; for a given &#x60;bibleId&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBibleTest() throws ApiException {
        String bibleId = null;
                InlineResponse2001 response = api.getBible(bibleId);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets an array of &#x60;Bible&#x60; objects authorized for current API Key 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBiblesTest() throws ApiException {
        String language = null;
        String abbreviation = null;
        String name = null;
        String ids = null;
        Boolean includeFullDetails = null;
                InlineResponse200 response = api.getBibles(language, abbreviation, name, ids, includeFullDetails);
        // TODO: test validations
    }
    
}
