/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher;

import de.evangeliumstaucher.invoker.ApiException;
import de.evangeliumstaucher.model.InlineResponse2006;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PassagesApi
 */
@Ignore
public class PassagesApiTest {

    private final PassagesApi api = new PassagesApi();

    
    /**
     * 
     *
     * Gets a &#x60;Passage&#x60; object for a given &#x60;bibleId&#x60; and &#x60;passageId&#x60;. This Passage object also includes an &#x60;content&#x60; property with all verses corresponding to the passageId. The &#x60;passageId&#x60; parameter can represent a chapter, verse, or range of verses. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPassageTest() throws ApiException {
        String bibleId = null;
        String passageId = null;
        String contentType = null;
        Boolean includeNotes = null;
        Boolean includeTitles = null;
        Boolean includeChapterNumbers = null;
        Boolean includeVerseNumbers = null;
        Boolean includeVerseSpans = null;
        String parallels = null;
        Boolean useOrgId = null;
                InlineResponse2006 response = api.getPassage(bibleId, passageId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels, useOrgId);
        // TODO: test validations
    }
    
}
