/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher;

import de.evangeliumstaucher.invoker.ApiException;
import de.evangeliumstaucher.model.InlineResponse2007;
import de.evangeliumstaucher.model.InlineResponse2008;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SectionsApi
 */
@Ignore
public class SectionsApiTest {

    private final SectionsApi api = new SectionsApi();

    
    /**
     * 
     *
     * Gets an array of &#x60;Section&#x60; objects for a given &#x60;bibleId&#x60; and &#x60;bookId&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBookSectionsTest() throws ApiException {
        String bibleId = null;
        String bookId = null;
                InlineResponse2007 response = api.getBookSections(bibleId, bookId);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets an array of &#x60;Section&#x60; objects for a given &#x60;bibleId&#x60; and &#x60;chapterId&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChapterSectionsTest() throws ApiException {
        String bibleId = null;
        String chapterId = null;
                InlineResponse2007 response = api.getChapterSections(bibleId, chapterId);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Gets a single &#x60;Section&#x60; object for a given &#x60;bibleId&#x60; and &#x60;sectionId&#x60;. This Section object also includes an &#x60;content&#x60; property with all verses for the Section. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectionTest() throws ApiException {
        String bibleId = null;
        String sectionId = null;
        String contentType = null;
        Boolean includeNotes = null;
        Boolean includeTitles = null;
        Boolean includeChapterNumbers = null;
        Boolean includeVerseNumbers = null;
        Boolean includeVerseSpans = null;
        String parallels = null;
                InlineResponse2008 response = api.getSection(bibleId, sectionId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels);
        // TODO: test validations
    }
    
}
