package de.evangeliumstaucher.app.utils;

import com.google.common.collect.Lists;
import lombok.Getter;

import java.util.List;

public class DatatableLanguages {

    @Getter
    private static final List<String> availableLanguages = Lists.newArrayList(
            "Afrikaans",
            "Albanian",
            "Amharic",
            "Arabic",
            "Armenian",
            "Azerbaijan",
            "Bangla",
            "Basque",
            "Belarusian",
            "Bulgarian",
            "Catalan",
            "traditional",
            "Chinese",
            "Croatian",
            "Czech",
            "Danish",
            "Dutch",
            "English",
            "Esperanto",
            "Estonian",
            "Filipino",
            "Finnish",
            "French",
            "Galician",
            "Georgian",
            "German",
            "Greek",
            "Gujarati",
            "Hebrew",
            "Hindi",
            "Hungarian",
            "Icelandic",
            "Alternative",
            "Indonesian",
            "Irish",
            "Italian",
            "Japanese",
            "Kazakh",
            "Khmer",
            "Korean",
            "Kurdish",
            "Kyrgyz",
            "Lao",
            "Latvian",
            "Lithuanian",
            "Macedonian",
            "Malay",
            "Mongolian",
            "Nepali",
            "Bokmal",
            "Nynorsk",
            "Pashto",
            "Persian",
            "Polish",
            "Brasil",
            "Portuguese",
            "Romanian",
            "Russian",
            "Serbian",
            "Serbian_latin",
            "Sinhala",
            "Slovak",
            "Slovenian",
            "Spanish",
            "Swahili",
            "Swedish",
            "Tajik",
            "Tamil",
            "Thai",
            "Turkish",
            "Ukrainian",
            "Urdu",
            "Uzbek",
            "Vietnamese",
            "Welsh",
            "telugu");

}
