/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Meta
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T23:51:10.720725+01:00[Europe/Berlin]")
public class Meta {
  public static final String SERIALIZED_NAME_FUMS = "fums";
  @SerializedName(SERIALIZED_NAME_FUMS)
  private String fums;

  public static final String SERIALIZED_NAME_FUMS_ID = "fumsId";
  @SerializedName(SERIALIZED_NAME_FUMS_ID)
  private String fumsId;

  public static final String SERIALIZED_NAME_FUMS_JS_INCLUDE = "fumsJsInclude";
  @SerializedName(SERIALIZED_NAME_FUMS_JS_INCLUDE)
  private String fumsJsInclude;

  public static final String SERIALIZED_NAME_FUMS_JS = "fumsJs";
  @SerializedName(SERIALIZED_NAME_FUMS_JS)
  private String fumsJs;

  public static final String SERIALIZED_NAME_FUMS_NO_SCRIPT = "fumsNoScript";
  @SerializedName(SERIALIZED_NAME_FUMS_NO_SCRIPT)
  private String fumsNoScript;

  public Meta() { 
  }

  public Meta fums(String fums) {
    
    this.fums = fums;
    return this;
  }

   /**
   * Get fums
   * @return fums
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFums() {
    return fums;
  }


  public void setFums(String fums) {
    this.fums = fums;
  }


  public Meta fumsId(String fumsId) {
    
    this.fumsId = fumsId;
    return this;
  }

   /**
   * Get fumsId
   * @return fumsId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFumsId() {
    return fumsId;
  }


  public void setFumsId(String fumsId) {
    this.fumsId = fumsId;
  }


  public Meta fumsJsInclude(String fumsJsInclude) {
    
    this.fumsJsInclude = fumsJsInclude;
    return this;
  }

   /**
   * Get fumsJsInclude
   * @return fumsJsInclude
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFumsJsInclude() {
    return fumsJsInclude;
  }


  public void setFumsJsInclude(String fumsJsInclude) {
    this.fumsJsInclude = fumsJsInclude;
  }


  public Meta fumsJs(String fumsJs) {
    
    this.fumsJs = fumsJs;
    return this;
  }

   /**
   * Get fumsJs
   * @return fumsJs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFumsJs() {
    return fumsJs;
  }


  public void setFumsJs(String fumsJs) {
    this.fumsJs = fumsJs;
  }


  public Meta fumsNoScript(String fumsNoScript) {
    
    this.fumsNoScript = fumsNoScript;
    return this;
  }

   /**
   * Get fumsNoScript
   * @return fumsNoScript
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFumsNoScript() {
    return fumsNoScript;
  }


  public void setFumsNoScript(String fumsNoScript) {
    this.fumsNoScript = fumsNoScript;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meta meta = (Meta) o;
    return Objects.equals(this.fums, meta.fums) &&
        Objects.equals(this.fumsId, meta.fumsId) &&
        Objects.equals(this.fumsJsInclude, meta.fumsJsInclude) &&
        Objects.equals(this.fumsJs, meta.fumsJs) &&
        Objects.equals(this.fumsNoScript, meta.fumsNoScript);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fums, fumsId, fumsJsInclude, fumsJs, fumsNoScript);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meta {\n");
    sb.append("    fums: ").append(toIndentedString(fums)).append("\n");
    sb.append("    fumsId: ").append(toIndentedString(fumsId)).append("\n");
    sb.append("    fumsJsInclude: ").append(toIndentedString(fumsJsInclude)).append("\n");
    sb.append("    fumsJs: ").append(toIndentedString(fumsJs)).append("\n");
    sb.append("    fumsNoScript: ").append(toIndentedString(fumsNoScript)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

