/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.evangeliumstaucher.model.SectionNext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Section
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T23:51:10.720725+01:00[Europe/Berlin]")
public class Section {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_BIBLE_ID = "bibleId";
  @SerializedName(SERIALIZED_NAME_BIBLE_ID)
  private String bibleId;

  public static final String SERIALIZED_NAME_BOOK_ID = "bookId";
  @SerializedName(SERIALIZED_NAME_BOOK_ID)
  private String bookId;

  public static final String SERIALIZED_NAME_CHAPTER_ID = "chapterId";
  @SerializedName(SERIALIZED_NAME_CHAPTER_ID)
  private String chapterId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content;

  public static final String SERIALIZED_NAME_VERSE_COUNT = "verseCount";
  @SerializedName(SERIALIZED_NAME_VERSE_COUNT)
  private Integer verseCount;

  public static final String SERIALIZED_NAME_FIRST_VERSE_ID = "firstVerseId";
  @SerializedName(SERIALIZED_NAME_FIRST_VERSE_ID)
  private String firstVerseId;

  public static final String SERIALIZED_NAME_LAST_VERSE_ID = "lastVerseId";
  @SerializedName(SERIALIZED_NAME_LAST_VERSE_ID)
  private String lastVerseId;

  public static final String SERIALIZED_NAME_FIRST_VERSE_ORG_ID = "firstVerseOrgId";
  @SerializedName(SERIALIZED_NAME_FIRST_VERSE_ORG_ID)
  private String firstVerseOrgId;

  public static final String SERIALIZED_NAME_LAST_VERSE_ORG_ID = "lastVerseOrgId";
  @SerializedName(SERIALIZED_NAME_LAST_VERSE_ORG_ID)
  private String lastVerseOrgId;

  public static final String SERIALIZED_NAME_COPYRIGHT = "copyright";
  @SerializedName(SERIALIZED_NAME_COPYRIGHT)
  private String copyright;

  public static final String SERIALIZED_NAME_NEXT = "next";
  @SerializedName(SERIALIZED_NAME_NEXT)
  private SectionNext next;

  public static final String SERIALIZED_NAME_PREVIOUS = "previous";
  @SerializedName(SERIALIZED_NAME_PREVIOUS)
  private SectionNext previous;

  public Section() { 
  }

  public Section id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public Section bibleId(String bibleId) {
    
    this.bibleId = bibleId;
    return this;
  }

   /**
   * Get bibleId
   * @return bibleId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBibleId() {
    return bibleId;
  }


  public void setBibleId(String bibleId) {
    this.bibleId = bibleId;
  }


  public Section bookId(String bookId) {
    
    this.bookId = bookId;
    return this;
  }

   /**
   * Get bookId
   * @return bookId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBookId() {
    return bookId;
  }


  public void setBookId(String bookId) {
    this.bookId = bookId;
  }


  public Section chapterId(String chapterId) {
    
    this.chapterId = chapterId;
    return this;
  }

   /**
   * Get chapterId
   * @return chapterId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getChapterId() {
    return chapterId;
  }


  public void setChapterId(String chapterId) {
    this.chapterId = chapterId;
  }


  public Section title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public Section content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    this.content = content;
  }


  public Section verseCount(Integer verseCount) {
    
    this.verseCount = verseCount;
    return this;
  }

   /**
   * Get verseCount
   * @return verseCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getVerseCount() {
    return verseCount;
  }


  public void setVerseCount(Integer verseCount) {
    this.verseCount = verseCount;
  }


  public Section firstVerseId(String firstVerseId) {
    
    this.firstVerseId = firstVerseId;
    return this;
  }

   /**
   * Get firstVerseId
   * @return firstVerseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFirstVerseId() {
    return firstVerseId;
  }


  public void setFirstVerseId(String firstVerseId) {
    this.firstVerseId = firstVerseId;
  }


  public Section lastVerseId(String lastVerseId) {
    
    this.lastVerseId = lastVerseId;
    return this;
  }

   /**
   * Get lastVerseId
   * @return lastVerseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastVerseId() {
    return lastVerseId;
  }


  public void setLastVerseId(String lastVerseId) {
    this.lastVerseId = lastVerseId;
  }


  public Section firstVerseOrgId(String firstVerseOrgId) {
    
    this.firstVerseOrgId = firstVerseOrgId;
    return this;
  }

   /**
   * Get firstVerseOrgId
   * @return firstVerseOrgId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFirstVerseOrgId() {
    return firstVerseOrgId;
  }


  public void setFirstVerseOrgId(String firstVerseOrgId) {
    this.firstVerseOrgId = firstVerseOrgId;
  }


  public Section lastVerseOrgId(String lastVerseOrgId) {
    
    this.lastVerseOrgId = lastVerseOrgId;
    return this;
  }

   /**
   * Get lastVerseOrgId
   * @return lastVerseOrgId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastVerseOrgId() {
    return lastVerseOrgId;
  }


  public void setLastVerseOrgId(String lastVerseOrgId) {
    this.lastVerseOrgId = lastVerseOrgId;
  }


  public Section copyright(String copyright) {
    
    this.copyright = copyright;
    return this;
  }

   /**
   * Get copyright
   * @return copyright
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCopyright() {
    return copyright;
  }


  public void setCopyright(String copyright) {
    this.copyright = copyright;
  }


  public Section next(SectionNext next) {
    
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SectionNext getNext() {
    return next;
  }


  public void setNext(SectionNext next) {
    this.next = next;
  }


  public Section previous(SectionNext previous) {
    
    this.previous = previous;
    return this;
  }

   /**
   * Get previous
   * @return previous
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SectionNext getPrevious() {
    return previous;
  }


  public void setPrevious(SectionNext previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Section section = (Section) o;
    return Objects.equals(this.id, section.id) &&
        Objects.equals(this.bibleId, section.bibleId) &&
        Objects.equals(this.bookId, section.bookId) &&
        Objects.equals(this.chapterId, section.chapterId) &&
        Objects.equals(this.title, section.title) &&
        Objects.equals(this.content, section.content) &&
        Objects.equals(this.verseCount, section.verseCount) &&
        Objects.equals(this.firstVerseId, section.firstVerseId) &&
        Objects.equals(this.lastVerseId, section.lastVerseId) &&
        Objects.equals(this.firstVerseOrgId, section.firstVerseOrgId) &&
        Objects.equals(this.lastVerseOrgId, section.lastVerseOrgId) &&
        Objects.equals(this.copyright, section.copyright) &&
        Objects.equals(this.next, section.next) &&
        Objects.equals(this.previous, section.previous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bibleId, bookId, chapterId, title, content, verseCount, firstVerseId, lastVerseId, firstVerseOrgId, lastVerseOrgId, copyright, next, previous);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Section {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bibleId: ").append(toIndentedString(bibleId)).append("\n");
    sb.append("    bookId: ").append(toIndentedString(bookId)).append("\n");
    sb.append("    chapterId: ").append(toIndentedString(chapterId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    verseCount: ").append(toIndentedString(verseCount)).append("\n");
    sb.append("    firstVerseId: ").append(toIndentedString(firstVerseId)).append("\n");
    sb.append("    lastVerseId: ").append(toIndentedString(lastVerseId)).append("\n");
    sb.append("    firstVerseOrgId: ").append(toIndentedString(firstVerseOrgId)).append("\n");
    sb.append("    lastVerseOrgId: ").append(toIndentedString(lastVerseOrgId)).append("\n");
    sb.append("    copyright: ").append(toIndentedString(copyright)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

