/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SectionSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T23:51:10.720725+01:00[Europe/Berlin]")
public class SectionSummary {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_BIBLE_ID = "bibleId";
  @SerializedName(SERIALIZED_NAME_BIBLE_ID)
  private String bibleId;

  public static final String SERIALIZED_NAME_BOOK_ID = "bookId";
  @SerializedName(SERIALIZED_NAME_BOOK_ID)
  private String bookId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_FIRST_VERSE_ID = "firstVerseId";
  @SerializedName(SERIALIZED_NAME_FIRST_VERSE_ID)
  private String firstVerseId;

  public static final String SERIALIZED_NAME_LAST_VERSE_ID = "lastVerseId";
  @SerializedName(SERIALIZED_NAME_LAST_VERSE_ID)
  private String lastVerseId;

  public static final String SERIALIZED_NAME_FIRST_VERSE_ORG_ID = "firstVerseOrgId";
  @SerializedName(SERIALIZED_NAME_FIRST_VERSE_ORG_ID)
  private String firstVerseOrgId;

  public static final String SERIALIZED_NAME_LAST_VERSE_ORG_ID = "lastVerseOrgId";
  @SerializedName(SERIALIZED_NAME_LAST_VERSE_ORG_ID)
  private String lastVerseOrgId;

  public SectionSummary() { 
  }

  public SectionSummary id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public SectionSummary bibleId(String bibleId) {
    
    this.bibleId = bibleId;
    return this;
  }

   /**
   * Get bibleId
   * @return bibleId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBibleId() {
    return bibleId;
  }


  public void setBibleId(String bibleId) {
    this.bibleId = bibleId;
  }


  public SectionSummary bookId(String bookId) {
    
    this.bookId = bookId;
    return this;
  }

   /**
   * Get bookId
   * @return bookId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBookId() {
    return bookId;
  }


  public void setBookId(String bookId) {
    this.bookId = bookId;
  }


  public SectionSummary title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public SectionSummary firstVerseId(String firstVerseId) {
    
    this.firstVerseId = firstVerseId;
    return this;
  }

   /**
   * Get firstVerseId
   * @return firstVerseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFirstVerseId() {
    return firstVerseId;
  }


  public void setFirstVerseId(String firstVerseId) {
    this.firstVerseId = firstVerseId;
  }


  public SectionSummary lastVerseId(String lastVerseId) {
    
    this.lastVerseId = lastVerseId;
    return this;
  }

   /**
   * Get lastVerseId
   * @return lastVerseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastVerseId() {
    return lastVerseId;
  }


  public void setLastVerseId(String lastVerseId) {
    this.lastVerseId = lastVerseId;
  }


  public SectionSummary firstVerseOrgId(String firstVerseOrgId) {
    
    this.firstVerseOrgId = firstVerseOrgId;
    return this;
  }

   /**
   * Get firstVerseOrgId
   * @return firstVerseOrgId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getFirstVerseOrgId() {
    return firstVerseOrgId;
  }


  public void setFirstVerseOrgId(String firstVerseOrgId) {
    this.firstVerseOrgId = firstVerseOrgId;
  }


  public SectionSummary lastVerseOrgId(String lastVerseOrgId) {
    
    this.lastVerseOrgId = lastVerseOrgId;
    return this;
  }

   /**
   * Get lastVerseOrgId
   * @return lastVerseOrgId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastVerseOrgId() {
    return lastVerseOrgId;
  }


  public void setLastVerseOrgId(String lastVerseOrgId) {
    this.lastVerseOrgId = lastVerseOrgId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionSummary sectionSummary = (SectionSummary) o;
    return Objects.equals(this.id, sectionSummary.id) &&
        Objects.equals(this.bibleId, sectionSummary.bibleId) &&
        Objects.equals(this.bookId, sectionSummary.bookId) &&
        Objects.equals(this.title, sectionSummary.title) &&
        Objects.equals(this.firstVerseId, sectionSummary.firstVerseId) &&
        Objects.equals(this.lastVerseId, sectionSummary.lastVerseId) &&
        Objects.equals(this.firstVerseOrgId, sectionSummary.firstVerseOrgId) &&
        Objects.equals(this.lastVerseOrgId, sectionSummary.lastVerseOrgId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bibleId, bookId, title, firstVerseId, lastVerseId, firstVerseOrgId, lastVerseOrgId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bibleId: ").append(toIndentedString(bibleId)).append("\n");
    sb.append("    bookId: ").append(toIndentedString(bookId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    firstVerseId: ").append(toIndentedString(firstVerseId)).append("\n");
    sb.append("    lastVerseId: ").append(toIndentedString(lastVerseId)).append("\n");
    sb.append("    firstVerseOrgId: ").append(toIndentedString(firstVerseOrgId)).append("\n");
    sb.append("    lastVerseOrgId: ").append(toIndentedString(lastVerseOrgId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

