/*
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.evangeliumstaucher;

import de.evangeliumstaucher.invoker.ApiCallback;
import de.evangeliumstaucher.invoker.ApiClient;
import de.evangeliumstaucher.invoker.ApiException;
import de.evangeliumstaucher.invoker.ApiResponse;
import de.evangeliumstaucher.invoker.Configuration;
import de.evangeliumstaucher.invoker.Pair;
import de.evangeliumstaucher.invoker.ProgressRequestBody;
import de.evangeliumstaucher.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import de.evangeliumstaucher.model.InlineResponse20010;
import de.evangeliumstaucher.model.InlineResponse2009;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VersesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public VersesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public VersesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getVerse
     * @param bibleId Id of Bible for passage (required)
     * @param verseId String reference id for the requested verse. (required)
     * @param contentType Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param includeNotes Include footnotes in content (optional, default to false)
     * @param includeTitles Include section titles in content (optional, default to true)
     * @param includeChapterNumbers Include chapter numbers in content (optional, default to false)
     * @param includeVerseNumbers Include verse numbers in content. (optional, default to true)
     * @param includeVerseSpans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param parallels Comma delimited list of bibleIds to include (optional)
     * @param useOrgId Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Passage not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVerseCall(String bibleId, String verseId, String contentType, Boolean includeNotes, Boolean includeTitles, Boolean includeChapterNumbers, Boolean includeVerseNumbers, Boolean includeVerseSpans, String parallels, Boolean useOrgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/bibles/{bibleId}/verses/{verseId}"
            .replaceAll("\\{" + "bibleId" + "\\}", localVarApiClient.escapeString(bibleId.toString()))
            .replaceAll("\\{" + "verseId" + "\\}", localVarApiClient.escapeString(verseId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (contentType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("content-type", contentType));
        }

        if (includeNotes != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("include-notes", includeNotes));
        }

        if (includeTitles != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("include-titles", includeTitles));
        }

        if (includeChapterNumbers != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("include-chapter-numbers", includeChapterNumbers));
        }

        if (includeVerseNumbers != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("include-verse-numbers", includeVerseNumbers));
        }

        if (includeVerseSpans != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("include-verse-spans", includeVerseSpans));
        }

        if (parallels != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("parallels", parallels));
        }

        if (useOrgId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("use-org-id", useOrgId));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getVerseValidateBeforeCall(String bibleId, String verseId, String contentType, Boolean includeNotes, Boolean includeTitles, Boolean includeChapterNumbers, Boolean includeVerseNumbers, Boolean includeVerseSpans, String parallels, Boolean useOrgId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'bibleId' is set
        if (bibleId == null) {
            throw new ApiException("Missing the required parameter 'bibleId' when calling getVerse(Async)");
        }
        
        // verify the required parameter 'verseId' is set
        if (verseId == null) {
            throw new ApiException("Missing the required parameter 'verseId' when calling getVerse(Async)");
        }
        

        okhttp3.Call localVarCall = getVerseCall(bibleId, verseId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels, useOrgId, _callback);
        return localVarCall;

    }

    /**
     * 
     * Gets a &#x60;Verse&#x60; object for a given &#x60;bibleId&#x60; and &#x60;verseId&#x60;. This Verse object also includes an &#x60;content&#x60; property with the verse corresponding to the verseId. 
     * @param bibleId Id of Bible for passage (required)
     * @param verseId String reference id for the requested verse. (required)
     * @param contentType Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param includeNotes Include footnotes in content (optional, default to false)
     * @param includeTitles Include section titles in content (optional, default to true)
     * @param includeChapterNumbers Include chapter numbers in content (optional, default to false)
     * @param includeVerseNumbers Include verse numbers in content. (optional, default to true)
     * @param includeVerseSpans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param parallels Comma delimited list of bibleIds to include (optional)
     * @param useOrgId Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     * @return InlineResponse20010
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Passage not found </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse20010 getVerse(String bibleId, String verseId, String contentType, Boolean includeNotes, Boolean includeTitles, Boolean includeChapterNumbers, Boolean includeVerseNumbers, Boolean includeVerseSpans, String parallels, Boolean useOrgId) throws ApiException {
        ApiResponse<InlineResponse20010> localVarResp = getVerseWithHttpInfo(bibleId, verseId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels, useOrgId);
        return localVarResp.getData();
    }

    /**
     * 
     * Gets a &#x60;Verse&#x60; object for a given &#x60;bibleId&#x60; and &#x60;verseId&#x60;. This Verse object also includes an &#x60;content&#x60; property with the verse corresponding to the verseId. 
     * @param bibleId Id of Bible for passage (required)
     * @param verseId String reference id for the requested verse. (required)
     * @param contentType Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param includeNotes Include footnotes in content (optional, default to false)
     * @param includeTitles Include section titles in content (optional, default to true)
     * @param includeChapterNumbers Include chapter numbers in content (optional, default to false)
     * @param includeVerseNumbers Include verse numbers in content. (optional, default to true)
     * @param includeVerseSpans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param parallels Comma delimited list of bibleIds to include (optional)
     * @param useOrgId Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     * @return ApiResponse&lt;InlineResponse20010&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Passage not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse20010> getVerseWithHttpInfo(String bibleId, String verseId, String contentType, Boolean includeNotes, Boolean includeTitles, Boolean includeChapterNumbers, Boolean includeVerseNumbers, Boolean includeVerseSpans, String parallels, Boolean useOrgId) throws ApiException {
        okhttp3.Call localVarCall = getVerseValidateBeforeCall(bibleId, verseId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels, useOrgId, null);
        Type localVarReturnType = new TypeToken<InlineResponse20010>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Gets a &#x60;Verse&#x60; object for a given &#x60;bibleId&#x60; and &#x60;verseId&#x60;. This Verse object also includes an &#x60;content&#x60; property with the verse corresponding to the verseId. 
     * @param bibleId Id of Bible for passage (required)
     * @param verseId String reference id for the requested verse. (required)
     * @param contentType Content type to be returned in the content property.  Supported values are &#x60;html&#x60; (default), &#x60;json&#x60; (beta), and &#x60;text&#x60; (beta) (optional, default to html)
     * @param includeNotes Include footnotes in content (optional, default to false)
     * @param includeTitles Include section titles in content (optional, default to true)
     * @param includeChapterNumbers Include chapter numbers in content (optional, default to false)
     * @param includeVerseNumbers Include verse numbers in content. (optional, default to true)
     * @param includeVerseSpans Include spans that wrap verse numbers and verse text for bible content. (optional, default to false)
     * @param parallels Comma delimited list of bibleIds to include (optional)
     * @param useOrgId Use the supplied id(s) to match the verseOrgId instead of the verseId (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Passage not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVerseAsync(String bibleId, String verseId, String contentType, Boolean includeNotes, Boolean includeTitles, Boolean includeChapterNumbers, Boolean includeVerseNumbers, Boolean includeVerseSpans, String parallels, Boolean useOrgId, final ApiCallback<InlineResponse20010> _callback) throws ApiException {

        okhttp3.Call localVarCall = getVerseValidateBeforeCall(bibleId, verseId, contentType, includeNotes, includeTitles, includeChapterNumbers, includeVerseNumbers, includeVerseSpans, parallels, useOrgId, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse20010>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getVerses
     * @param bibleId Id of Bible whose Verses to fetch (required)
     * @param chapterId Id of the Chapter whose Verses to fetch (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Book not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVersesCall(String bibleId, String chapterId, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/bibles/{bibleId}/chapters/{chapterId}/verses"
            .replaceAll("\\{" + "bibleId" + "\\}", localVarApiClient.escapeString(bibleId.toString()))
            .replaceAll("\\{" + "chapterId" + "\\}", localVarApiClient.escapeString(chapterId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getVersesValidateBeforeCall(String bibleId, String chapterId, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'bibleId' is set
        if (bibleId == null) {
            throw new ApiException("Missing the required parameter 'bibleId' when calling getVerses(Async)");
        }
        
        // verify the required parameter 'chapterId' is set
        if (chapterId == null) {
            throw new ApiException("Missing the required parameter 'chapterId' when calling getVerses(Async)");
        }
        

        okhttp3.Call localVarCall = getVersesCall(bibleId, chapterId, _callback);
        return localVarCall;

    }

    /**
     * 
     * Gets an array of &#x60;Verse&#x60; objects for a given &#x60;bibleId&#x60; and &#x60;chapterId&#x60; 
     * @param bibleId Id of Bible whose Verses to fetch (required)
     * @param chapterId Id of the Chapter whose Verses to fetch (required)
     * @return InlineResponse2009
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Book not found </td><td>  -  </td></tr>
     </table>
     */
    public InlineResponse2009 getVerses(String bibleId, String chapterId) throws ApiException {
        ApiResponse<InlineResponse2009> localVarResp = getVersesWithHttpInfo(bibleId, chapterId);
        return localVarResp.getData();
    }

    /**
     * 
     * Gets an array of &#x60;Verse&#x60; objects for a given &#x60;bibleId&#x60; and &#x60;chapterId&#x60; 
     * @param bibleId Id of Bible whose Verses to fetch (required)
     * @param chapterId Id of the Chapter whose Verses to fetch (required)
     * @return ApiResponse&lt;InlineResponse2009&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Book not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InlineResponse2009> getVersesWithHttpInfo(String bibleId, String chapterId) throws ApiException {
        okhttp3.Call localVarCall = getVersesValidateBeforeCall(bibleId, chapterId, null);
        Type localVarReturnType = new TypeToken<InlineResponse2009>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Gets an array of &#x60;Verse&#x60; objects for a given &#x60;bibleId&#x60; and &#x60;chapterId&#x60; 
     * @param bibleId Id of Bible whose Verses to fetch (required)
     * @param chapterId Id of the Chapter whose Verses to fetch (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid ID supplied </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized for API access.  Missing or Invalid API Token provided. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Not authorized to retrieve Sections for this Bible </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Book not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getVersesAsync(String bibleId, String chapterId, final ApiCallback<InlineResponse2009> _callback) throws ApiException {

        okhttp3.Call localVarCall = getVersesValidateBeforeCall(bibleId, chapterId, _callback);
        Type localVarReturnType = new TypeToken<InlineResponse2009>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
